### ISSUE TITLE
Any documentation available ?

### ISSUE THREAD

**Issue by alexandre-romain** [worldline/sips-sdk-php#2]
Hi,

I'm trying to implement this solution on a website. I'm having lots of difficulties and was wondering where I could find some more documentation as this repo doesn't contain any.

Thanks for your answer

**Comment by nicolasros** [comment]
Hi,

to get the latest documentation, send an email to supportsips-benelux@worldline.com and request the JSON paypage documentation and the data dictionary.

kind regards,
Nicolas
