### ISSUE TITLE
Inconsistency problem with response on PaypageResult

### ISSUE THREAD

**Issue by dive-michiel** [worldline/sips-sdk-php#5]
Null values are returned both as null or "null" (string) (see attached screenshot).

PaypageResult expects all properties to be strings resulting in errors on the getters where the response returned null instead of "null" as a string.

```
    /**
     * @return string
     */
    public function getAcquirerNativeResponseCode(): string
    {
        return $this->acquirerNativeResponseCode;
    }
```

## Possible solutions

1) Convert all null responses to null (on the api level) and change the response types to `? string`to allow for null values
2) Convert all null values to strings in the response (on the api level)

<img width="504" alt="Screenshot 2019-10-25 at 15 37 10" src="https://user-images.githubusercontent.com/2650975/67575749-851f5680-f73d-11e9-9baf-de84206fb55c.png">

**Comment by nicolasros** [comment]
When it is "null" (a string) it means Sips returned null.
When it is just null, it means that the value was not present in the response.
I would like to keep this distinction.

I did add the nullable return types to the getters of PaypageResult. (release 1.0.3)

**Comment by dive-michiel** [comment]
Thanks!
